### ISSUE TITLE
Translations in ELAN documents

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#21]
In 5 ELAN documents the translation tier seems not to be indicated as such but as a transcription tier. As a consequence, the translations appear as regular utterances (`<u>` elements) in the TEI output (being tokenized etc.) These documents are affected:

- [ ] 103_tei_w/Urfa-029_Smoking-Harran-2010.xml
- [ ] 103_tei_w/Urfa-034_Liquorice-Harran-2010.xml
- [ ] 103_tei_w/Urfa-043_Truffle-Harran-2010.xml
- [ ] 103_tei_w/Urfa-070_Hen_House-Harran-2010.xml
- [ ] 103_tei_w/Urfa-075_Corn_and_Language-Harran-2010.xml

Please format them as the other ones. Thank you!

**Comment by miriamalt** [comment]
I am trying to solve the problem

**Comment by aozanh97** [comment]
and I just pushed the changes. It should be fine now

**Comment by rausch-supola** [comment]
29, 34, 43, 44, 70, 72, 73, 74, 75, 112, 140, 150

**Comment by miriamaltawil** [comment]
Ok, I worked on those from 29 to 72. Can you give me a feedback before I finish with the last 6? 
Is the translation tier now subordinated to the transcription one? From my side it seems to have worked

**Comment by dasch124** [comment]
Dear Miriam, looks good to me! You can check yourself: When you open the generated TEI-version of the changed document, the translation should be placed into a `<spanGrp>` element  (see e.g. line [243](https://github.com/acdh-oeaw/shawi-data/blob/6c743d5eefe5feb32f5f74cd11f8c75580ae8431/103_tei_w/Urfa-029_Smoking-Harran-2010.xml#L243)

**Comment by dasch124** [comment]
Thank you, @miriamaltawil ! Yes, looks good now! 
You can check for yourself: It worked, when the translation is placed within a `<spanGrp>` element in the generated TEI document in 103_tei_w. E.g. [here](https://github.com/acdh-oeaw/shawi-data/blob/6c743d5eefe5feb32f5f74cd11f8c75580ae8431/103_tei_w/Urfa-029_Smoking-Harran-2010.xml#L243). You might need to wait for some seconds for the transformation process to run through and commit the TEI documents.

**Comment by miriamaltawil** [comment]
That's good news! I will continue then; I will be done on Monday with this :)

**Comment by miriamaltawil** [comment]
Ok, the issue tier-type is solved in all elan files mentioned above.

**Comment by dasch124** [comment]
Great, that was quick, @miriamaltawil ! I went over the changes really quickly, and this looks solved to me. 

@rausch-supola Can you please double-check? Thank you! 

The only remaining issue is that we seem to have inconsistent names for the tiers or tier type. Can you change them to "Translation" in the following files?

* Urfa-011_Cemetry-Harran-2010.eaf
* Urfa-012_Lentils-Harran-2010.eaf
* Urfa-029_Smoking-Harran-2010.eaf
* Urfa-042_Hospitality-Harran-2010.eaf
* Urfa-077a_The_Jinn-Harran-2010.eaf
* Urfa-077_Jinn-Harran-2010.pfsx
* Urfa-092_Sultan_Murad-Harran-2010.eaf
* Urfa-094_Three_Advices-Harran-2010.eaf

Thank you!

**Comment by miriamaltawil** [comment]
sure! I will do it

**Comment by miriamaltawil** [comment]
I have worked on the first 5 files. I am not sure it worked... (?)

**Comment by dasch124** [comment]
looks good!

**Comment by rausch-supola** [comment]
Unfortunately, there occured another file which differs from the others: 085. And there seems to be two of them: "Urfa-085_Snake_in_the_Cistern-Harran-2010.xml" and "Urfa-085_The_snake.xml". They both have _who="#Transcription"_ without exception.

**Comment by miriamaltawil** [comment]
I think I fixed the issue... Let me know if it worked.

**Comment by rausch-supola** [comment]
Thank you, everything seems to look fine with "Urfa-085_The_Snake_in_the_Cistern-Harran-2010". The problem is still there with "Urfa-085_Snake_in_the_Cistern-Harran-2010.xml" and "Urfa-085_The_snake.xml" - maybe these are no longer needed?

**Comment by rausch-supola** [comment]
seems this is fixed @dasch124 ?
